CREATE PROCEDURE insertUser(IN ID BIGINT)
	MODIFIES SQL DATA
	BEGIN ATOMIC
		INSERT INTO USERS (ID, NAME, GIVEN_NAME) VALUES (ID, 'overloadName1', 'overloadGivenName1');
	END/;
	
CREATE PROCEDURE insertUser(IN ID BIGINT, IN BIRTH_DATE TIMESTAMP)
	MODIFIES SQL DATA
	BEGIN ATOMIC
		INSERT INTO USERS (ID, NAME, GIVEN_NAME, BIRTH_DATE) VALUES (ID, 'overloadName2', 'overloadGivenName2', BIRTH_DATE);
	END/;
	
CREATE PROCEDURE findUserById(INOUT ID_P BIGINT, OUT NAME VARCHAR(100), OUT GIVEN_NAME VARCHAR(100), OUT BIRTH_DATE TIMESTAMP) 
	READS SQL DATA
	BEGIN ATOMIC
		-- this statement uses the id to get firstname and lastname
		SELECT U.ID, U.NAME, U.GIVEN_NAME, U.BIRTH_DATE INTO ID_P, NAME, GIVEN_NAME, BIRTH_DATE FROM USERS U WHERE U.ID = ID_P;
	END/;