CREATE PROCEDURE insertUser(IN ID BIGINT)
	MODIFIES SQL DATA
	BEGIN ATOMIC
		INSERT INTO USERS (ID, NAME, GIVEN_NAME) VALUES (ID, 'overloadName1', 'overloadGivenName1');
	END/;
	
CREATE PROCEDURE insertUser(IN ID BIGINT, IN BIRTH_DATE TIMESTAMP)
	MODIFIES SQL DATA
	BEGIN ATOMIC
		INSERT INTO USERS (ID, NAME, GIVEN_NAME, BIRTH_DATE) VALUES (ID, 'overloadName2', 'overloadGivenName2', BIRTH_DATE);
	END/;
	
CREATE PROCEDURE findUserById(INOUT ID_P BIGINT, OUT NAME VARCHAR(100), OUT GIVEN_NAME VARCHAR(100), OUT BIRTH_DATE TIMESTAMP) 
	READS SQL DATA
	BEGIN ATOMIC
		-- this statement uses the id to get firstname and lastname
		SELECT U.ID, U.NAME, U.GIVEN_NAME, U.BIRTH_DATE INTO ID_P, NAME, GIVEN_NAME, BIRTH_DATE FROM USERS U WHERE U.ID = ID_P;
	END/;
	
CREATE PROCEDURE findAllUsers()
	READS SQL DATA DYNAMIC RESULT SETS 1
	BEGIN ATOMIC
		DECLARE USERS_ASC  CURSOR WITH RETURN FOR SELECT U.ID, U.NAME, U.GIVEN_NAME, U.BIRTH_DATE FROM USERS U ORDER BY U.ID ASC;
		DECLARE USERS_DESC CURSOR WITH RETURN FOR SELECT U.ID, U.NAME, U.GIVEN_NAME, U.BIRTH_DATE FROM USERS U ORDER BY U.ID DESC;
		OPEN USERS_ASC;
		OPEN USERS_DESC;
	END/;
   
CREATE PROCEDURE findAllUsersAndProperty(OUT PROPERTY VARCHAR(100))
	READS SQL DATA DYNAMIC RESULT SETS 1
	BEGIN ATOMIC
		DECLARE USERS_ASC  CURSOR WITH RETURN FOR SELECT U.ID, U.NAME, U.GIVEN_NAME, U.BIRTH_DATE FROM USERS U ORDER BY U.ID ASC;
		DECLARE USERS_DESC CURSOR WITH RETURN FOR SELECT U.ID, U.NAME, U.GIVEN_NAME, U.BIRTH_DATE FROM USERS U ORDER BY U.ID DESC;
		SET PROPERTY = 'TEST';
		OPEN USERS_ASC;
		OPEN USERS_DESC;
	END/;
	
CREATE FUNCTION countUsers()
	RETURNS INTEGER READS SQL DATA
	BEGIN ATOMIC
		DECLARE nbUsers INTEGER;
		SET nbUsers = SELECT COUNT(*) FROM USERS U;
		RETURN nbUsers;
	END/;

CREATE FUNCTION countUsersWithIn(IN PARAM_IN INTEGER)
	RETURNS INTEGER READS SQL DATA
	BEGIN ATOMIC
		DECLARE nbUsers INTEGER;
		SET nbUsers = SELECT COUNT(*) FROM USERS U;
		RETURN nbUsers;
	END/;
	