CREATE PROCEDURE insertUser(IN ID BIGINT)
	MODIFIES SQL DATA
	BEGIN ATOMIC
		INSERT INTO USERS (ID, NAME, GIVEN_NAME) VALUES (ID, 'overloadName1', 'overloadGivenName1');
	END/;
	
CREATE PROCEDURE insertUser(IN ID BIGINT, IN BIRTH_DATE TIMESTAMP)
	MODIFIES SQL DATA
	BEGIN ATOMIC
		INSERT INTO USERS (ID, NAME, GIVEN_NAME, BIRTH_DATE) VALUES (ID, 'overloadName2', 'overloadGivenName2', BIRTH_DATE);
	END/;